ERROR:root:could not convert string to float: 'Hel'
ERROR:root:could not convert string to float: 'world'
ERROR:root:ADDITION ERROR!!! unsupported operand type(s) for +: 'float' and 'ValueError'.
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\functions.py", line 30, in addition
    result = sum(numbers);
             ^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'float' and 'ValueError'
ERROR:root:Error in main program!!!
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\main.py", line 10, in main
    return functions.__dict__[operation](numbers)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'fsdfdsaa'
ERROR:root:could not convert string to float: '"Hello"'
ERROR:root:could not convert string to float: ' abc'
ERROR:root:multiplication EXCEPTION!!! unsupported operand type(s) for *: 'float' and 'ValueError'.
ERROR:root:Error in main program!!!
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\main.py", line 10, in main
    return functions.__dict__.get(operation)(numbers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
ERROR:root:could not convert string to float: 'hello'
ERROR:root:could not convert string to float: 'True'
ERROR:root:could not convert string to float: 'None'
ERROR:root:could not convert string to float: "'Hello'\\n"
ERROR:root:Error in main program!!!
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\functions.py", line 42, in subtraction
    result = reduce(lambda accumulator, value: accumulator-value, numbers);
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\functions.py", line 42, in <lambda>
    result = reduce(lambda accumulator, value: accumulator-value, numbers);
                                               ~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'ValueError'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\main.py", line 10, in main
    return functions.__dict__.get(operation)(numbers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Desktop\practice\Python\PYTHON\PYTHON-\logging\calculator\functions.py", line 45, in subtraction
    logging.error(f"FROM: {__name__}. ERROR: subtraction EXCEPTION!!! {dict(File=__name__, EXC=EXC)}.", exc_info={dict(file=__name__, exception=EXC)});
                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
